name: release
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag to release (must start with "v", e.g., v1.2.3)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        architecture: [ 'x64' ]

    name: Release ${{ github.event.inputs.release-tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.release-tag }}

      - name: Validate release tag format
        run: |
          TAG="${{ github.event.inputs.release-tag }}"
          
          if [[ ! "$TAG" =~ ^v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9]+)?$ ]]; then
            echo "❌ Invalid tag format: '${{ github.event.inputs.release-tag }}'"
            echo "✅ Tag must start with 'v' and follow semantic versioning (e.g., v1.0.0 or v1.2.3-RC1)"
            exit 1
          fi
          
          if ! git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "❌ Tag '$TAG' does not exist in the repository"
            exit 1
          fi

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: central
          # MAVEN_CENTRAL_USERNAME and MAVEN_CENTRAL_PASSWORD are environment variable names
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Release
        run: mvn -B --no-transfer-progress -Pmaven-central-release -DskipTests=true deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          # MAVEN_GPG_PASSPHRASE is the default environment variable name for the GPG passphrase
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.event.inputs.release-tag }}" --generate-notes --title "${{ github.event.inputs.release-tag }}"
        env:
          # GITHUB_TOKEN for GitHub CLI must be set manually
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

